---
- name: Ensure tmp directory exists
  file: path="{{ sparkles_dir }}/tmp" state=directory owner=root mode=0777

- name: Ensure modules directory exists
  file: path="{{ sparkles_dir }}/modules" state=directory owner=root mode=0777

- name: Ensure etc directory exists
  file: path="{{ sparkles_dir }}/etc" state=directory owner=root mode=0777

- name: copy config.yml.template in etc
  action: template dest="{{ sparkles_dir }}/etc/config.yml.template" src=roles/sparkles/files/config.yml.template owner=root group=root mode=0777
